#include "fastllm-gguf-mmq-kernels.cuh"

namespace fastllm_gguf_mmq {
FASTLLM_INSTANTIATE_MMQ(GGML_TYPE_Q2_K)
FASTLLM_INSTANTIATE_MMQ(GGML_TYPE_Q3_K)
FASTLLM_INSTANTIATE_MMQ(GGML_TYPE_Q4_K)
FASTLLM_INSTANTIATE_MMQ(GGML_TYPE_Q5_K)
FASTLLM_INSTANTIATE_MMQ(GGML_TYPE_Q6_K)
} // namespace fastllm_gguf_mmq
