file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
# Six length/boundary cases and eight executed lifecycle requests; each
# emits seven steps of 256 FP32 logits. The pre-forward abort emits nothing.
# Greedy/sampling mode switches additionally emit 102 checked token IDs.
math(EXPR expected_bytes "(6 + 8) * 7 * 256 * 4 + 102 * 4")
foreach(mode eager graph failbegin failinstantiate)
    set(output "${TEST_DIRECTORY}/${mode}.bin")
    file(REMOVE "${output}")
    execute_process(COMMAND "${TEST_EXECUTABLE}" "${mode}" "${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 180)
    if (result STREQUAL "77")
        message(STATUS "FASTLLM_TEST_SKIP_NO_DEVICE")
        return()
    endif()
    if (NOT result STREQUAL "0" OR NOT stdout MATCHES "TP GRAPH MODEL PASS")
        message(FATAL_ERROR "Naive TP ${mode} failed (${result}):\n${stdout}\n${stderr}")
    endif()
    if (NOT EXISTS "${output}")
        message(FATAL_ERROR "Naive TP ${mode} did not write logits")
    endif()
    file(SIZE "${output}" bytes)
    if (NOT bytes EQUAL expected_bytes)
        message(FATAL_ERROR "Naive TP ${mode}: expected ${expected_bytes} logit bytes, got ${bytes}")
    endif()
    file(SHA256 "${output}" digest)
    if (mode STREQUAL "eager")
        set(reference "${digest}")
    elseif (NOT digest STREQUAL reference)
        message(FATAL_ERROR "Naive TP ${mode} logits differ from eager")
    endif()
    message(STATUS "Naive TP ${mode}: PASS")
endforeach()
