file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
foreach(mode eager graph failbegin failinstantiate)
    set(output "${TEST_DIRECTORY}/${mode}.bin")
    file(REMOVE "${output}")
    execute_process(COMMAND "${TEST_EXECUTABLE}" "${mode}" "${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 180)
    if (result STREQUAL "77")
        message(STATUS "FASTLLM_TEST_SKIP_NO_DEVICE")
        return()
    endif()
    if (NOT result STREQUAL "0" OR NOT stdout MATCHES "TP GRAPH MODEL PASS")
        message(FATAL_ERROR "Naive TP ${mode} failed (${result}):\n${stdout}\n${stderr}")
    endif()
    if (NOT EXISTS "${output}")
        message(FATAL_ERROR "Naive TP ${mode} did not write logits")
    endif()
    file(SIZE "${output}" bytes)
    if (NOT bytes EQUAL 43008)
        message(FATAL_ERROR "Naive TP ${mode}: expected 43008 logit bytes, got ${bytes}")
    endif()
    file(SHA256 "${output}" digest)
    if (mode STREQUAL "eager")
        set(reference "${digest}")
    elseif (NOT digest STREQUAL reference)
        message(FATAL_ERROR "Naive TP ${mode} logits differ from eager")
    endif()
    message(STATUS "Naive TP ${mode}: PASS")
endforeach()
